---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

params:
  MAVEN_OPTS:
  MAVEN_CONFIG:

# outputs:
#   - name: build

run:
  path: mvnw
  args: [
     clean,
     package,
     -DskipTests
  ]
