---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

params:
  MAVEN_OPTS:
  MAVEN_CONFIG:

inputs:
  - name: app

# run:
#   path: sh
#   args:
#   - -exc
#   - |
#     whoami
#     env
#     find .

run:
 path: mvnw
 dir: app
 args: [
   clean,
   test
 ]
